### ISSUE TITLE
Difficulty installing cardioception

### ISSUE THREAD

**Issue by MalloryJfeldman** [embodied-computation-group/Cardioception#53]
Hey! I'm relatively new to python and can't figure out what's going on -- I keep getting the following error: 

```
Collecting psychopy>=2020.1.2
  Using cached PsychoPy-2022.2.2.zip (26.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /private/var/folders/l6/rw9jlvzx185bqxwpk43j385m0000gn/T/pip-install-a69fs8cu/psychopy_77e79aeb6e4043fd84efbcbfde5421ff/setup.py:28: SetuptoolsDeprecationWarning: As setuptools moves its configuration towards `pyproject.toml`,
      `setuptools.config.read_configuration` became deprecated.
      
      For the time being, you can use the `setuptools.config.setupcfg` module
      to access a backward compatible API, but this module is provisional
      and might be removed in the future.
      
        required = read_configuration('setup.cfg')['options']['install_requires']
      /opt/anaconda3/lib/python3.8/site-packages/setuptools/config/setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/l6/rw9jlvzx185bqxwpk43j385m0000gn/T/pip-install-a69fs8cu/psychopy_77e79aeb6e4043fd84efbcbfde5421ff/setup.py", line 41, in <module>
          required.remove('pyqt5; python_version >= "3"')
      ValueError: list.remove(x): x not in list
      [end of output]
```
Any help to resolve would be appreciated

**Comment by LegrandNico** [comment]
Hi @MalloryJfeldman ,

So this looks like an error related to the installation of Psychopy. What command did you use here? It tries to install `2020.1.2` but there is already another version `2022.2.2`. I would recommend making sure that Psychopy is completely uninstalled (both the standalone version and the package) before trying again. Then you can pin a specific version with `pip install psychopy==2020.1.2`.
